version: '3.1'

services:
  springboot:
    image: ashish1412/spring-boot-mongo:VERSION
    environment:
    - MONGO_DB_HOSTNAME=mongo
    ports:
      - 8081:8080
    networks:
    - springappnetwork
  mongo:
    image: mongo
    volumes:
      - mongodb:/data/db
    networks:
    - springappnetwork 
    
volumes:
  mongodb:
    driver: local
    
networks:
  springappnetwork:
    driver: bridge
